[package]
authors = ["FL03 <jo3mccain@icloud.com> (https://github.com/FL03)"]
categories = []
description = "Puzzled"
edition = "2021"
homepage = "https://github.com/FL03/pzzld-gateway/wiki"
keywords = []
license = "Apache-2.0"
name = "pzzld"
repository = "https://github.com/FL03/pzzld-gateway"
version = "0.1.0"

[[bin]]
bench = true
name = "gateway"
path = "src/main.rs"
test = false

[build-dependencies]

[dependencies]
acme = { features = ["net"], git = "https://github.com/FL03/acme", branch = "v0.2.5", version = "0.2.5" }
pzzld-gateway = { features = [], path = "../gateway", version = "0.1.0" }
scsys = { features = ["full"], version = "0.1.40" }

async-session = "3.0.0"
async-trait = "0.1.60"
axum = { features = ["headers", "http2", "macros", "ws"], version = "0.6.1" }
clap = { features = ["derive"], version = "4.0.29" }
futures = "0.3.25"
glob = "0.3.0"
http = "0.2.8"
hyper = { features = ["full"], version = "0.14.23" }
redis = { features = ["tokio"], version = "0.22" }
reqwest = { features = ["json", "rustls-tls", "stream"], version = "0.11" }
serde = { features = ["derive"], version = "1" }
serde_json = "1"
strum = { features = ["derive"], version = "0.24" }
tokio = { features = ["full"], version = "1" }
tokio-stream = "0.1.11"
tower = "0.4.13"
tower-http = { features = ["full"], version = "0.3.5" }
tracing = "0.1.36"
tracing-subscriber = { features = ["env-filter"], version = "0.3.16" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
